gpu_id: 0
training_batch_size: 1024
data_path: './data'

USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
TIME_FIELD: 'timestamp'

load_col:
    inter: ['user_id', 'item_id', 'timestamp']

eval_args:
    group_by: user
    order: RO
    split: {'LS': 'test_only'}
    mode: full
