gpu_id: 0
learning_rate: 0.001
epochs: 500
train_batch_size: 4096
eval_batch_size: 4096
data_path: './data/'
embedding_size: 16
seq_separator: '@'
USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
TIME_FIELD: 'timestamp'
RATING_FIELD: ~
dropout_prob: 0.5
eval_step: 1
load_col:
    inter: ['user_id', 'item_id', 'timestamp']
    user: ['user_id', 'popularity']
    item: ['item_id', 'title', 'year', 'genre', 'director', 'writer']
unused_col:
    inter: ['timestamp']
neg_sampling: {'uniform': 1, 'dynamic': 2}
eval_args:
    group_by: user
    order: RO
    split: {"RS": [8, 1, 1]}
    mode: full
# user_inter_num_interval: [11,138493]
# item_inter_num_interval: [1,119145]
# fields: {0: ['user_id','popularity'], 1: ['item_id', 'title', 'year', 'genre', 'director', 'writer']}
# MAX_ITEM_LIST_LENGTH: 50
topk: 10
metrics: ['Recall']
valid_metric: Recall@10