data_path: ./ml_comp
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
load_col: {"inter": ["user_id", "item_id", "timestamp"]}
neg_sampling: {"uniform": 1}
mf_embedding_size: 64
mlp_embedding_size: 64
mlp_hidden_size: "[128, 64]"
dropout_prob: 0.1
mf_train: True
mlp_train: True
use_pretrain: False

epochs: 50
train_batch_size: 256
eval_batch_size: 4096
eval_args:
    split: {"RS": "[9, 1, 0]"}
    group_by: user
    order: TO
    mode: full
    repeatable: False

valid_metric: Recall@10
